#
# Message in A bottle Docker Compose file
#

#3.1.27.4
version: "3.6"

services:
  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      # this is only for development purpose
      - "5342:5342"
    env_file:
      - env_file

  mib_users:
    <<: &mib_users
      # Building the image
      image: "mib-users:latest"
      build:
        context: .
        dockerfile: Dockerfile 

    ports:
     - "5001:5001"
    env_file:
      - env_file
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
      - redis

  redis:
    image: redis

  celery-beat:
    image: celery
    build: .
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: celery -A background beat -l info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND_URL=redis://redis:6379/0
      - C_FORCE_ROOT=true

  celery-work:
    image: celery
    build: .
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: celery -A background worker -l info
    depends_on:
      - redis
      - celery-beat
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND_URL=redis://redis:6379/0
      - C_FORCE_ROOT=true


# Declaring all volumes
volumes:
  pgdata: # for maintaing db data
